# Pivot Basics

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("weather.csv")
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [3]:
df.pivot(index='city',columns='date')

         temperature                   humidity
date        5/1/2017 5/2/2017 5/3/2017 5/1/2017 5/2/2017 5/3/2017
city
beijing           80       77       79       26       30       35
mumbai            75       78       82       80       83       85
new york          65       66       68       56       58       60

In [4]:
df.pivot(index='city',columns='date',values='humidity')

date      5/1/2017  5/2/2017  5/3/2017
city
beijing         26        30        35
mumbai          80        83        85
new york        56        58        60

In [5]:
df.pivot(index='date',columns='city')

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [6]:
df.pivot(index='humidity',columns='city')

              date                     temperature
city       beijing    mumbai  new york     beijing mumbai new york
humidity
26        5/1/2017       NaN       NaN        80.0    NaN      NaN
30        5/2/2017       NaN       NaN        77.0    NaN      NaN
35        5/3/2017       NaN       NaN        79.0    NaN      NaN
56             NaN       NaN  5/1/2017         NaN    NaN     65.0
58             NaN       NaN  5/2/2017         NaN    NaN     66.0
60             NaN       NaN  5/3/2017         NaN    NaN     68.0
80             NaN  5/1/2017       NaN         NaN   75.0      NaN
83             NaN  5/2/2017       NaN         NaN   78.0      NaN
85             NaN  5/3/2017       NaN         NaN   82.0      NaN

### Pivot Table

In [7]:
df=pd.read_csv("weather2.csv")
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [8]:
df.pivot_table(index='city',columns='date',aggfunc='count')

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai          2        2           2        2
new york        2        2           2        2

## Margins

In [ ]:
df.pivot_table(index="city",columns="date",margins=True,aggfunc=np.sum)

C:\Users\shubham\AppData\Local\Temp\ipykernel_5572\225491910.py:1: FutureWarning: The provided callable <function sum at 0x0000024F64004EE0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index="city",columns="date",aggfunc=np.sum)

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai        163      111         153      162
new york      110      122         126      142

## Grouper

In [11]:
df=pd.read_csv("weather3.csv")
df

        date      city  temperature  humidity
0   5/1/2017  new york           65        56
1   5/2/2017  new york           61        54
2   5/3/2017  new york           70        60
3  12/1/2017  new york           30        50
4  12/2/2017  new york           28        52
5  12/3/2017  new york           25        51

In [17]:
df['date']=pd.to_datetime(df['date'])
df

        date      city  temperature  humidity
0 2017-05-01  new york           65        56
1 2017-05-02  new york           61        54
2 2017-05-03  new york           70        60
3 2017-12-01  new york           30        50
4 2017-12-02  new york           28        52
5 2017-12-03  new york           25        51

In [16]:
df.pivot_table(index=pd.Grouper(freq='ME',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667