### Basic Concatenation

In [1]:
import pandas as pd

In [2]:
india_weather=pd.DataFrame({
    "city":["mumbai","delhi","bangalore"],
    "temperature":[32,45,30],
    "humidity":[80,60,78]
})
india_weather

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78

In [3]:
us_weather=pd.DataFrame({
    "city":["newyork","chicago","boston"],
    "temperature":[21,14,35],
    "humidity":[68,65,75]
})
us_weather

      city  temperature  humidity
0  newyork           21        68
1  chicago           14        65
2   boston           35        75

In [4]:
df=pd.concat([india_weather,us_weather])
df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78
0    newyork           21        68
1    chicago           14        65
2     boston           35        75

## Ignore index

In [5]:
df=pd.concat([india_weather,us_weather],ignore_index=True)
df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78
3    newyork           21        68
4    chicago           14        65
5     boston           35        75

In [6]:
df=pd.concat([india_weather,us_weather],keys=["india","us"])
df

              city  temperature  humidity
india 0     mumbai           32        80
      1      delhi           45        60
      2  bangalore           30        78
us    0    newyork           21        68
      1    chicago           14        65
      2     boston           35        75

In [8]:
df.loc["us"]

      city  temperature  humidity
0  newyork           21        68
1  chicago           14        65
2   boston           35        75

In [9]:
df.loc["india"]

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78