In [6]:
import pandas as pd
from word2number import w2n

In [7]:
df=pd.read_csv("hiring.csv")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
df.experience=df.experience.fillna("zero")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [9]:

df.experience=df.experience.apply(w2n.word_to_num)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [13]:
import math as mt
ts=mt.floor(df["test_score(out of 10)"].mean())
ts

7

In [18]:
df["test_score(out of 10)"]=df["test_score(out of 10)"].fillna(ts)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

In [23]:
lr.predict([[2,9,6]])

C:\Users\v-srsaur\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

In [25]:
lr.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [27]:
lr.intercept_

14992.65144669314

In [28]:
2922.26901502 * 2 + 2221.30909959 * 9 + 2147.48256637 * 6 + 14992.65144669314

53713.86677126314