# Read/Write  CSV and Excel files in Pandas

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("stock_data.csv")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [4]:
df=pd.read_csv("stock_data.csv",skiprows=1)
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [5]:
df=pd.read_csv("stock_data.csv",header=1)
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [6]:
df=pd.read_csv("stock_data.csv",header=None,names=["ticker","eps","revenue","people"])
df

                ticker      eps revenue         people
tickers            eps  revenue   price         people
GOOGL            27.82       87     845     larry page
WMT               4.61      484      65           n.a.
MSFT                -1       85      64     bill gates
RIL      not available       50    1023  mukesh ambani
TATA               5.6       -1    n.a.     ratan tata

In [7]:
df=pd.read_csv("stock_data.csv",nrows=2)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [10]:
df=pd.read_csv("stock_data.csv",na_values=["n.a.","not available"])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [12]:
df=pd.read_csv("stock_data.csv",na_values={
    'eps':['not available'],
    'revenue': [-1],
    'people': ['not available','n.a.']
})
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [13]:
df.to_csv("new.csv",index=False)

In [14]:
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [15]:
df.to_csv("new.csv",header=False)