Different ways of creating Dataframe

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

# Using Excel

In [4]:
df=pd.read_excel("weather_data.xlsx")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

# Using Dictionary

In [5]:
weather_data={
    'day':['1/1/2017','1/2/2017','1/3/2017'],
    'temperature':[32,335,28],
    'windspeed': [6,7,2],
    'event': ['Rain','Sunny','Snow']
}
df=pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017          335          7  Sunny
2  1/3/2017           28          2   Snow

# Using Tuples

In [7]:
weather_data=[
    (1/1/2017,32,6,'Rain'),
    (1/2/2017,35,7,'Sunny'),
    (1/3/2017,28,2,'Snow')
]

df=pd.DataFrame(data=weather_data,columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  0.000496           32          6   Rain
1  0.000248           35          7  Sunny
2  0.000165           28          2   Snow

# Using list of dicionaries

In [9]:
weather_data=[
    {'day':'1/1/2017','temperature':32,'windspeed':6,'event':'Rain'},
    {'day':'1/2/2017','temperature':35,'windspeed':7,'event':'Snow'},
    {'day':'1/3/2017','temperature':28,'windspeed':2,'event':'Sunny'}
]
df=pd.DataFrame(data=weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7   Snow
2  1/3/2017           28          2  Sunny