## Inner join ---> Returns only the rows with keys in both dataframes
## Outer join ----> Returns all rows from both dataframes . Fills in NaN's where there is no match
## Left Join ----> returns all the rows from the left dataframe and matched rows from the right
## Right join -----> returns all rows from the right dataframe and matched rows from the left

In [1]:
import pandas as pd

In [2]:
df1=pd.DataFrame({
    'id': [1,2,3,4],
    'name':['Alice','Bob','Charlie','David']
})

df2=pd.DataFrame({
    'id': [3,4,5,6],
    'score':[85,90,95,88]
})

In [4]:
display(df1)
display(df2)

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David

   id  score
0   3     85
1   4     90
2   5     95
3   6     88

In [5]:
# Inner join
inner_merge=pd.merge(df1,df2,on='id',how='inner')
display(inner_merge)

   id     name  score
0   3  Charlie     85
1   4    David     90

In [7]:
# Outer join
outer_merge=pd.merge(df1,df2,on='id',how='outer')
display(outer_merge)

   id     name  score
0   1    Alice    NaN
1   2      Bob    NaN
2   3  Charlie   85.0
3   4    David   90.0
4   5      NaN   95.0
5   6      NaN   88.0

In [8]:
#left join
left_merge=pd.merge(df1,df2,on='id',how='left')
display(left_merge)

   id     name  score
0   1    Alice    NaN
1   2      Bob    NaN
2   3  Charlie   85.0
3   4    David   90.0

In [9]:
#Right join
right_merge=pd.merge(df1,df2,on='id',how='right')
right_merge

   id     name  score
0   3  Charlie     85
1   4    David     90
2   5      NaN     95
3   6      NaN     88