In [1]:
import pandas as pd
df=pd.read_excel("Saurabh_Test_Data.xlsx")
df.head()

,Owning Subsidiary (Marketing Project) (Marketing Project),Task ID,Active Stage,Service Type,Audience (Marketing Project) (Marketing Project),Created On,Service Task Type,Platform,Record Status (Service Request) (Service Request),Service Line (Service Type) (MASH Service)
0,Australia,ST789891,Additional Review,Targeted List Pull,Commercial,2023-01-15 18:33:43,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement
1,Australia,ST789922,Additional Review,Targeted List Pull,Commercial,2023-01-15 20:34:04,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement
2,Australia,ST791779,Additional Review,Targeted List Pull,Commercial,2023-01-17 18:04:34,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement
3,Australia,ST791834,Additional Review,Targeted List Pull,Commercial,2023-01-17 18:46:22,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement
4,Australia,ST791971,Build,Targeted List Pull,Commercial,2023-01-17 23:34:41,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement

In [2]:
df['Created On'] = pd.to_datetime(df['Created On'], errors='coerce')

In [5]:
type(df['Created On'])

pandas.core.series.Series

In [6]:
df['Created On'] = pd.to_datetime(df['Created On'].dt.date)

In [7]:
df.head()

,Owning Subsidiary (Marketing Project) (Marketing Project),Task ID,Active Stage,Service Type,Audience (Marketing Project) (Marketing Project),Created On,Service Task Type,Platform,Record Status (Service Request) (Service Request),Service Line (Service Type) (MASH Service)
0,Australia,ST789891,Additional Review,Targeted List Pull,Commercial,2023-01-15,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement
1,Australia,ST789922,Additional Review,Targeted List Pull,Commercial,2023-01-15,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement
2,Australia,ST791779,Additional Review,Targeted List Pull,Commercial,2023-01-17,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement
3,Australia,ST791834,Additional Review,Targeted List Pull,Commercial,2023-01-17,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement
4,Australia,ST791971,Build,Targeted List Pull,Commercial,2023-01-17,Campaign Counts,Marketo,Completed,Lead Acquisition & Engagement

In [11]:
df['Created On'].iloc[0]

Timestamp('2023-01-15 00:00:00')

In [13]:
df1=df.groupby(df['Created On'])

In [14]:
df1