In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [3]:
new_df=df.replace(-99999,value=np.NaN)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [4]:
new_df = df.replace(to_replace=[-99999,-88888], value=0)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            0          7  Sunny
2  1/3/2017           28          0   Snow
3  1/4/2017            0          7      0
4  1/5/2017           32          0   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

## Replacing by using mapping

In [ ]:
new_df=df.replace({
    -99999: np.nan,
    'no event'
})